# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
